name: Deploy to neocities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Dependencies
      uses: BSFishy/pip-action@v1
      with:
        packages: autosite

    - name: Autosite
      run: autosite -a

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        neocities_supporter: false
        preview_before_deploy: true
        dist_dir: out